replicaCount: 1

image:
  repository: ""
  name: hello-world
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: alb
  hosts:
    - host: <URL_DNS>
      paths:
        - path: /
          pathType: Prefix
  tls: []